### ISSUE TITLE
Create a doc on `how-to-recover-seed-on-atomicdex-mobile`

### ISSUE THREAD

**Issue by gcharang** [KomodoPlatform/komodo-docs-mdx#101]
It is required in `src/pages/atomicdex/mobile/delete-seed-from-atomicdex-mobile/index.mdx`

**Comment by harsenyan3** [comment]
It is merged with a doc on how to recover private keys but it already exists, it's the "how to export/view private keys or/and seed phrase in komodo wallet mobile".
