### ISSUE TITLE
Technical docs (NN management related)

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/komodo-docs-mdx#15]
Setup guide needs an update for season 7.
- Ubuntu 18.04 is now EOL, so need to confirm deps for 20.04
- Needs section for virtualisation of 3P iguana/coins in main server

We could also add a couple of docs regarding things like 
- running komodod as a service
- setting up logrotate for mm2/chains
- implementing telegram / discord alerts

etc.

**Comment by gcharang** [comment]
why not consider Ubuntu 22.04 lts ?

**Comment by smk762** [comment]
Probably good to cover both, as both are in LTS and will be for the expected duration of the season.

**Comment by smk762** [comment]
Closing (until next season). In quiet times we might add some "bonus content" like telegram in their own issue tickets
