### ISSUE TITLE
"ContextPrivKey" option of "priv_key_policy" is written with lowercase k in "key" in some places

### ISSUE THREAD

**Issue by shamardy** [KomodoPlatform/komodo-docs-mdx#172]
ref https://github.com/KomodoPlatform/komodo-defi-framework/issues/2017#issuecomment-1847673250

**Comment by smk762** [comment]
fixed in https://github.com/KomodoPlatform/komodo-docs-mdx/pull/132/commits/3776be79afc9a8430d554f2069788d4d2e17b52c
