### ISSUE TITLE
 Rename dropdown menu names with first capital letter

### ISSUE THREAD

**Issue by endrilickollari** [KomodoPlatform/komodo-docs-mdx#22]
Currently, the dropdown menu names are not capitalized. As a menu name I think they should be starting with a capital letter.

![image](https://user-images.githubusercontent.com/32954585/236414337-45455dc4-e2ad-4b5b-a15d-bdeb79d6d951.png)

**Comment by gcharang** [comment]
done https://polish.komodo-docs-revamp-2023.pages.dev/en/docs/atomicdex/tutorials/listing-a-coin-on-atomicdex/
