### ISSUE TITLE
Coins file listing guide missing

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/komodo-docs-mdx#24]
Link on old site: - https://developers.komodoplatform.com/basic-docs/atomicdex/atomicdex-tutorials/listing-a-coin-on-atomicdex.html

**Comment by gcharang** [comment]
added https://polish.komodo-docs-revamp-2023.pages.dev/en/docs/atomicdex/tutorials/listing-a-coin-on-atomicdex/
