### ISSUE TITLE
Add event_streaming_configuration to mm2 config docs

### ISSUE THREAD

**Issue by harsenyan3** [KomodoPlatform/komodo-docs-mdx#277]
Add event_stream_configuration property to mm2 configuration docs. This property implements streaming channels using mpsc(underlying part of SSE) and SSE for sending data to clients continuously. 

Refer to PR#1945 for further information and details (https://github.com/KomodoPlatform/komodo-defi-framework/pull/1945#issue-1863081443)

**Comment by smk762** [comment]
closed by https://github.com/KomodoPlatform/komodo-docs-mdx/pull/307
