### ISSUE TITLE
Add "balance event streaming" info to docs

### ISSUE THREAD

**Issue by harsenyan3** [KomodoPlatform/komodo-docs-mdx#278]
Electrum docs don't seem to include any info about balance event streaming. 
Review PR#2013 (https://github.com/KomodoPlatform/komodo-defi-framework/pull/2013#issue-2008755914) for more info. 
Do for UTXO, EVM/eth, tendermint and ARRR/Pirate.

**Comment by shamardy** [comment]
related https://github.com/KomodoPlatform/komodo-docs-mdx/issues/277

**Comment by smk762** [comment]
closed by https://github.com/KomodoPlatform/komodo-docs-mdx/pull/307
