### ISSUE TITLE
Add info on Error Events to docs

### ISSUE THREAD

**Issue by harsenyan3** [KomodoPlatform/komodo-docs-mdx#279]
Add info on Error Events (UTXO, ETH and tendermint). 
For technical details and specs refer to PR#2041 (https://github.com/KomodoPlatform/komodo-defi-framework/pull/2041).

**Comment by shamardy** [comment]
related https://github.com/KomodoPlatform/komodo-docs-mdx/issues/277

**Comment by smk762** [comment]
closed by https://github.com/KomodoPlatform/komodo-docs-mdx/pull/307
