### ISSUE TITLE
Add v2 "my_swap_status" and "my_recent_swaps" RPC info on docs.

### ISSUE THREAD

**Issue by harsenyan3** [KomodoPlatform/komodo-docs-mdx#280]
Add info on docs about v2 "my_swap_status" and "my_recent_swaps" RPC methods. Also modify v1 methods to include the possibility of returning upgraded swaps data.

Refer to [PR#2015](https://github.com/KomodoPlatform/komodo-defi-framework/pull/2015) for more info.

**Comment by smk762** [comment]
Docs update for `my_recent_swaps` in https://github.com/KomodoPlatform/komodo-docs-mdx/pull/294
