### ISSUE TITLE
Add "active_swaps" v2 RPC info to docs

### ISSUE THREAD

**Issue by harsenyan3** [KomodoPlatform/komodo-docs-mdx#281]
Add info on "active_swaps" v2 RPC methods to docs. Refer to [PR#2046](https://github.com/KomodoPlatform/komodo-defi-framework/pull/2046) for specifics and more info.

**Comment by smk762** [comment]
@AndrewDelaney please post progress towards this task at your earliest conveniece.

**Comment by AndrewDelaney** [comment]
@smk762, I have created the page for this method. I will push today, I'm just checking if there's anything else I can include.
