### ISSUE TITLE
Add "max_concurrent_connections" param in mm2 config

### ISSUE THREAD

**Issue by harsenyan3** [KomodoPlatform/komodo-docs-mdx#282]
Add info on new "max_concurrent_connections" param in mm2 config. For further info refer to [PR#2063](https://github.com/KomodoPlatform/komodo-defi-framework/pull/2063).

**Comment by smk762** [comment]
No doc edits needed, API PR purely internal.

**Comment by shamardy** [comment]
@smk762 There was a `max_concurrent_connections` config param that was added and can be used to override the default value of `512` if needed. https://github.com/KomodoPlatform/komodo-defi-framework/blob/df6ab98b3b2ee84918bfc0bf1bc03d1e1f219985/mm2src/mm2_main/src/lp_native_dex.rs#L588-L590 not sure if that needs to be documented or not though.
