### ISSUE TITLE
ibc transfers possible in withdraw method

### ISSUE THREAD

**Issue by harsenyan3** [KomodoPlatform/komodo-docs-mdx#283]
Add info on the possibility of ibc (inter-blockchain communication) transfers in the withdraw RPC method thanks to refactoring for tendermint. Check out [PR#2088](https://github.com/KomodoPlatform/komodo-defi-framework/pull/2088) for further info.

**Comment by shamardy** [comment]
This https://github.com/KomodoPlatform/komodo-defi-framework/pull/2088 also adds pubkey only activation for Tendermint and adds `send_asked_data` RPC and `DATA_NEEDED` Event. These all can be used for external wallets such as Keplr.
