### ISSUE TITLE
Update sign_raw_transaction rpc method docs

### ISSUE THREAD

**Issue by harsenyan3** [KomodoPlatform/komodo-docs-mdx#292]
There is a new param in sign_raw_transaction rpc to support eip-1559. 
The parameter is "pay_for_gas", it is optional. Sample below:
`      "tx": {
            "to": "0x7Bc1bBDD6A0a722fC9bffC49c921B685ECB84b94".to_string(),
            "value": "1.234",
            "gas_limit": "21000",
            "pay_for_gas": {
                "tx_type": "Eip1559",
                "max_fee_per_gas": "1234.567",
                "max_priority_fee_per_gas": "1.2",
            }
`
for more info refer to https://github.com/KomodoPlatform/komodo-defi-framework/pull/2051#issuecomment-2117979019

**Comment by smk762** [comment]
@ShantanuSharma9873 please report on progress towards this task at your earliest convenience.
