### ISSUE TITLE
Add docs for Heartbeat events

### ISSUE THREAD

**Issue by shamardy** [KomodoPlatform/komodo-docs-mdx#298]
Event named `HEARTBEAT` was added to streaming channel, this event can be used to know that streaming channel is working even if there are no new events are not broadcasted (no changes in balances, etc.., that need to be broadcasted)
ref. https://github.com/KomodoPlatform/komodo-defi-framework/pull/2058

**Comment by shamardy** [comment]
related to https://github.com/KomodoPlatform/komodo-docs-mdx/issues/277

**Comment by smk762** [comment]
closed by https://github.com/KomodoPlatform/komodo-docs-mdx/pull/307
