### ISSUE TITLE
breaking changes on proxy params

### ISSUE THREAD

**Issue by onur-ozkan** [KomodoPlatform/komodo-docs-mdx#311]
tendermint activation payloads and komodo-defi-proxy params have breaking change as explained in https://github.com/KomodoPlatform/komodo-defi-framework/pull/2173.

FWIW previous param "rpc_urls" is not documented on [this page](https://komodoplatform.com/en/docs/komodo-defi-framework/api/v20/enable_tendermint_with_assets).

**Comment by smk762** [comment]
Resolved in https://github.com/KomodoPlatform/komodo-docs-mdx/pull/318
