### ISSUE TITLE
`get_peers_info` RPC documentation is misleading and outdated

### ISSUE THREAD

**Issue by onur-ozkan** [KomodoPlatform/komodo-docs-mdx#316]
`get_peers_info` RPC is only returns currently connected seed nodes, not all network peers. And with  https://github.com/KomodoPlatform/komodo-defi-framework/pull/2195 PR, it's now called `get_directly_connected_peers`.

**Comment by smk762** [comment]
closed by https://github.com/KomodoPlatform/komodo-docs-mdx/pull/324
