### ISSUE TITLE
Link to FractionalValue not found

### ISSUE THREAD

**Issue by dimxy** [KomodoPlatform/komodo-docs-mdx#395]
When I click a link to `FractionalValue` on page https://komodoplatform.com/en/docs/komodo-defi-framework/api/legacy/buy/
I receive '404 Not Found error

**Comment by smk762** [comment]
Thanks for the report!
We did notice that in some cases, generated urls were missing a part of the path. Actual URL is https://komodoplatform.com/en/docs/komodo-defi-framework/api/common_structures/#fractional-value

The `/en/docs/` part was missing. I think @gcharang fixed this (pls confirm)

**Comment by dimxy** [comment]
Thanks

**Comment by gcharang** [comment]
yes, published the updated version yesterday
