### ISSUE TITLE
Sidebar failing to update for some pages

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/komodo-docs-mdx#53]
Github seems to be failing to upload images or video, so to replicate:
- Go to https://komodo-docs-revamp-2023.pages.dev/en/docs/atomicdex/api/v20-dev/
- Select `mobile` from the `AtomicDEX` dropdown menu.

**Comment by gcharang** [comment]
for me, sidebar changed. but, to a non-relevant one. will fix

**Comment by gcharang** [comment]
closing in favour of https://github.com/KomodoPlatform/komodo-docs-mdx/issues/61
