### ISSUE TITLE
PR validation workflow

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/komodo-docs-mdx#58]
There are a couple of things that we need to make sure are in each doc to make sure it works as in intended when building. 
For example:
- H1 header tags must be present for SEO (see https://github.com/gcharang/komodo-docs-revamp-2023/pull/24)
- We need to make sure any template placeholders have been edited to what they should be (see https://github.com/KomodoPlatform/komodo-docs-mdx/pull/56/commits/3c259c506140ffe3038668e09dfa77aba02dc175)
- Misc extra style guide validation

Might be others, this we can add to this issue when found.

**Comment by gcharang** [comment]
all the above and more issues will be caught by the current PR validation gh action scripts
